export const FETCH_ALL_REQUEST = 'FETCH_ALL_REQUEST'
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS'
export const FETCH_ALL_FAILURE = 'FETCH_ALL_FAILURE'

export const CREATE_REQUEST = 'CREATE_REQUEST'
export const CREATE_SUCCESS = 'CREATE_SUCCESS'
export const CREATE_FAILURE = 'CREATE_FAILURE'

export const DELETE_REQUEST = 'DELETE_REQUEST'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const DELETE_FAILURE = 'DELETE_FAILURE'

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_CLEARED = 'AUTH_CLEARED'
export const LOGOUT = "LOGOUT"

export const RES_MOVIES_REQUEST = 'RES_MOVIES_REQUEST'
export const RES_MOVIES_SUCCESS = 'RES_MOVIES_SUCCESS'
export const RES_MOVIES_FAILURE = 'RES_MOVIES_FAILURE'

export const RES_MOVIES_TIME_REQUEST = 'RES_MOVIES_TIME_REQUEST'
export const RES_MOVIES_TIME_SUCCESS = 'RES_MOVIES_TIME_SUCCESS'
export const RES_MOVIES_TIME_FAILURE = 'RES_MOVIES_TIME_FAILURE'

export const RES_MOVIES_SEAT_REQUEST = 'RES_MOVIES_SEAT_REQUEST'
export const RES_MOVIES_SEAT_SUCCESS = 'RES_MOVIES_SEAT_SUCCESS'
export const RES_MOVIES_SEAT_FAILURE = 'RES_MOVIES_SEAT_FAILURE'
